export default {
  ROUTE: "ROUTE",
  LIST_POKEMONS: "LIST_POKEMONS",
  CREATE_POKEMON: "CREATE_POKEMON",
  FILTER_POKEMONS: "FILTER_POKEMONS",
  SHOW_POKEMON: "SHOW_POKEMON",
  SELECT_POKEMON: "SELECT_POKEMON",
  DELETE_POKEMON: "DELETE_POKEMON",
  SHOW_LOADING: "SHOW_LOADING",
  HIDE_LOADING: "HIDE_LOADING"
};
